speech_recognition:
  phi_4_multimodal_instruct:
    enabled: true
  gemini_3_1_flash_lite_preview:
    enabled: true
  gemini_2_5_pro:
    enabled: true
  amazon_nova_multimodal_embeddings:
    enabled: true

language_translation:
  phi_4_multimodal_instruct:
    enabled: false
  gemini_3_1_flash_lite_preview:
    enabled: false
  gemini_2_5_pro:
    enabled: false
  amazon_nova_multimodal_embeddings:
    enabled: false
