speech_recognition:
  gpt_4o:
    enabled: false
  gemini_2_5_flash_lite:
    enabled: false
  phi_4_multimodal_instruct:
    enabled: true

language_translation:
  gpt_4o:
    enabled: false
  gemini_2_5_flash_lite:
    enabled: false
  phi_4_multimodal_instruct:
    enabled: true
