speech_recognition:
  phi_4_multimodal_instruct:
    enabled: false
  gemini_3_1_flash_lite_preview:
    enabled: false
  gemini_2_5_pro:
    enabled: false
  gpt_realtime_1_5:
    enabled: true
  gpt_realtime_mini:
    enabled: true

language_translation:
  phi_4_multimodal_instruct:
    enabled: false
  gemini_3_1_flash_lite_preview:
    enabled: false
  gemini_2_5_pro:
    enabled: false
  qwen_2_5_omni_7b:
    enabled: false
