speech_recognition:
  google_cloud_stt:
    enabled: false
  assemblyai:
    enabled: false
  aws_transcribe:
    enabled: false
  ibm_watson_stt:
    enabled: true
  speechmatics_stt:
    enabled: false
  deepgram_stt:
    enabled: false

language_translation:
  google_cloud_translation:
    enabled: false
  aws_translate:
    enabled: false
  microsoft_translator:
    enabled: true
  deepl_translation:
    enabled: false
  apptek:
    enabled: false
  modern_mt:
    enabled: false

emotion_detection:
  faceplusplus:
    enabled: true
  microsoft_azure_face:
    enabled: true
  aws_rekognition:
    enabled: true
  luxand_facesdk:
    enabled: true
  smartclick:
    enabled: false