speech_recognition:
  google_cloud_stt:
    enabled: true
  assemblyai:
    enabled: true
  aws_transcribe:
    enabled: true
  ibm_watson_stt:
    enabled: true
  speechmatics_stt:
    enabled: true
  deepgram_stt:
    enabled: true

language_translation:
  google_cloud_translation:
    enabled: true
  aws_translate:
    enabled: true
  microsoft_translator:
    enabled: true
  deepl_translation:
    enabled: true
